# Generated by Django 6.0.4 on 2026-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('voter_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
